monolog:
    channels:
        - ehyiah_apidoc_bundle

    handlers:
        mapping:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.apidoc_bundle.log"
            level: debug
            channels: ["ehyiah_apidoc_bundle"]
