services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Ehyiah\ApiDocBundle\:
        resource: '../src/'
        exclude:
            - '../src/Attributes/'
            - '../src/DependencyInjection/'
            - '../src/Exception/'
            - '../src/Kernel.php'

    Ehyiah\ApiDocBundle\Command\ComponentGeneration\GenerateComponentTuiCommand:
        arguments:
            $generators: !tagged_iterator ehyiah_api_doc.tui_generator

    Ehyiah\ApiDocBundle\Command\ComponentGeneration\Tui\SchemaTuiGenerator:
        tags: ['ehyiah_api_doc.tui_generator']
