services:
    _defaults:
        autowire: true
        autoconfigure: true

    Ehyiah\ApiDocBundle\:
        resource: '../src/'
        exclude:
            - '../src/Attributes/'
            - '../src/DependencyInjection/'
            - '../src/Exception/'
            - '../src/Kernel.php'

    Ehyiah\ApiDocBundle\Command\ComponentGeneration\GenerateComponentTuiCommand:
        arguments:
            $generators: !tagged_iterator ehyiah_api_doc.tui_generator
